name: Deploy Flask App to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: aks-flask-rg
        cluster-name: flask-aks-cluster

    - name: Log in to ACR
      run: az acr login --name flaskacr2025

    - name: Build and Push Docker image to ACR
      run: |
        docker build -t flaskacr2025.azurecr.io/flask-app:latest .
        docker push flaskacr2025.azurecr.io/flask-app:latest

    - name: Deploy to AKS
      run: |
        kubectl set image deployment/flask-app flask-container=flaskacr2025.azurecr.io/flask-app:latest
